# config/fail2ban-jail.conf
# Week 4: Intrusion Detection
# Copy to: /etc/fail2ban/jail.local
# Install: sudo apt install fail2ban -y

[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 5
ignoreip = 127.0.0.1/8

[sshd]
enabled  = true
port     = ssh
logpath  = /var/log/auth.log
maxretry = 3

[nodejs-api]
enabled  = true
port     = 3000
filter   = nodejs-api
logpath  = /path/to/week4-project/logs/security.log
maxretry = 5
bantime  = 1800
